apiVersion: v1
kind: ConfigMap
metadata:
  name: oathkeeper-env
  labels:
    app: oathkeeper
    component: api-gateway
data:
  OATHKEEPER_KRATOS_WHOAMI_URL: "http://kratos-public.web3.svc.cluster.local:4433/sessions/whoami"
  OATHKEEPER_KRATOS_PUBLIC_URL: "http://kratos-public.web3.svc.cluster.local:4433"
  OATHKEEPER_HYDRA_INTROSPECTION_URL: "http://hydra-admin.web3.svc.cluster.local:4445/admin/oauth2/introspect"
  OATHKEEPER_BACKEND_URL: "http://web3-api.web3.svc.cluster.local:8080"
  OATHKEEPER_ISSUER_URL: "http://oathkeeper-api.web3.svc.cluster.local:4456/"
  OATHKEEPER_ERROR_REDIRECT_URL: "http://localhost:3000/error"
  OATHKEEPER_API_CORS_ALLOWED_ORIGINS: "http://localhost:3000,http://localhost:3001"
  LOG_LEVEL: "debug"
  LOG_FORMAT: "json"
