apiVersion: v1
kind: ConfigMap
metadata:
  name: web3-frontend-config
data:
  config.json: |
    {
      "gatewayUrl": "https://gateway.web3-local-dev.com",
      "clientId": "web3-test-app",
      "authDomain": "app.web3-local-dev.com"
    }
