apiVersion: v1
kind: Service
metadata:
  name: web3-api
  labels:
    app: web3-api
    component: backend
spec:
  type: ClusterIP
  selector:
    app: web3-api
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
