apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: web3

resources:
- ../../base
- configmap-env.yaml
- configmap-config.yaml
- ingress.yaml

patches:
- path: patch-deployment.yaml
  target:
    kind: Deployment
    name: web3-api

labels:
- pairs:
    environment: minikube
images:
- name: web3-account-api
  newName: web3-account-api
  newTag: 20260326_v0_0_74
