apiVersion: apps/v1
kind: Deployment
metadata:
  name: spicedb-deployment
  labels:
    app: spicedb
    component: authorization
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spicedb
  template:
    metadata:
      labels:
        app: spicedb
        component: authorization
    spec:
      containers:
        - name: spicedb
          image: authzed/spicedb:latest
          command: ["spicedb"]
          args:
            - serve
          envFrom:
            - configMapRef:
                name: spicedb-env
          ports:
            - name: grpc
              containerPort: 50051
              protocol: TCP
            - name: http
              containerPort: 8443
              protocol: TCP
            - name: metrics
              containerPort: 9090
              protocol: TCP
          readinessProbe:
            exec:
              command: ["grpc_health_probe", "-addr=localhost:50051"]
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          livenessProbe:
            exec:
              command: ["grpc_health_probe", "-addr=localhost:50051"]
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: "1"
              memory: 1Gi
