#!/bin/bash
# Update ERC20 token icons and ERC721/ERC1155 blacklisted metadata in Blockscout Postgres
# Reads seed-addresses.json (generated by test-interact)
set -e

CONTEXT="${MINIKUBE_PROFILE:-web3-lab}"
NAMESPACE="${NAMESPACE:-web3}"
MINIO_BASE="http://localhost:9000/web3lab-assets"

if [ ! -f contracts/seed-addresses.json ]; then
  echo "❌ contracts/seed-addresses.json not found! Run 'make test-interact' first."
  exit 1
fi

echo "🎨 Updating ERC20 token icons in Blockscout Postgres..."

# Read ERC20 addresses and update icon_url
for i in $(seq 0 3); do
  ADDR=$(python3 -c "import json; d=json.load(open('contracts/seed-addresses.json')); print(d['erc20'][$i]['address'].lower())")
  SYMBOL=$(python3 -c "import json; d=json.load(open('contracts/seed-addresses.json')); print(d['erc20'][$i]['symbol'])")
  INDEX=$(python3 -c "import json; d=json.load(open('contracts/seed-addresses.json')); print(d['erc20'][$i]['index'])")
  ICON_URL="${MINIO_BASE}/erc20/${INDEX}.png"
  
  echo "  ↳ ${SYMBOL} (${ADDR}) → ${ICON_URL}"
  
  kubectl --context "${CONTEXT}" -n "${NAMESPACE}" exec -i sts/blockscout-postgres -- \
    psql -U blockscout -d blockscout -c \
    "UPDATE tokens SET icon_url = '${ICON_URL}' WHERE contract_address_hash = decode('${ADDR#0x}', 'hex');" \
    2>/dev/null
done

echo ""
echo "🖼️  Updating ERC721 NFT metadata in Blockscout Postgres..."

ERC721_ADDR=$(python3 -c "import json; d=json.load(open('contracts/seed-addresses.json')); print(d['erc721'][0]['address'].lower())")
ERC721_ADDR_HEX="${ERC721_ADDR#0x}"

NAMES=("Crystalline Ascension" "Floating Enchanted Island" "Cyberpunk Artifact" "Ethereal Ghost Creature")
DESCS=("A unique digital crystal artwork" "A rare collectible floating island" "Glowing neon ancient artifact" "A legendary glowing creature")

for i in 0 1 2 3; do
  IMG="${MINIO_BASE}/erc721/images/${i}.png"
  META="{\"name\":\"${NAMES[$i]}\",\"description\":\"${DESCS[$i]}\",\"image\":\"${IMG}\"}"
  
  echo "  ↳ NFT #${i}: ${NAMES[$i]}"
  
  kubectl --context "${CONTEXT}" -n "${NAMESPACE}" exec -i sts/blockscout-postgres -- \
    psql -U blockscout -d blockscout -c \
    "UPDATE token_instances SET metadata = '${META}'::jsonb, error = NULL WHERE token_contract_address_hash = decode('${ERC721_ADDR_HEX}', 'hex') AND token_id = ${i};" \
    2>/dev/null
done

echo ""
echo "✅ Token icons and NFT metadata updated! Refresh Blockscout to see the changes."
