apiVersion: v1
kind: ConfigMap
metadata:
  name: hydra-env
  labels:
    app: hydra
    component: oauth2-server
data:
  DSN: "postgres://postgres:postgres@auth-postgres.web3.svc.cluster.local:5432/hydra?sslmode=disable"
  SECRETS_SYSTEM_0: "web3-lab-hydra-secret-not-for-production"
  URLS_SELF_ISSUER: "https://gateway.web3-local-dev.com"
  URLS_CONSENT: "https://gateway.web3-local-dev.com/api/v1/oauth2/consent"
  URLS_LOGIN: "https://gateway.web3-local-dev.com/api/v1/oauth2/login"
  URLS_LOGOUT: "https://gateway.web3-local-dev.com/api/v1/oauth2/logout"
  URLS_POST_LOGOUT_REDIRECT: "https://app.web3-local-dev.com/?logout=true"
  SERVE_PUBLIC_CORS_ALLOWED_ORIGINS: "https://app.web3-local-dev.com,https://gateway.web3-local-dev.com,http://localhost:3000"
  SERVE_ADMIN_CORS_ALLOWED_ORIGINS: "https://app.web3-local-dev.com,https://gateway.web3-local-dev.com,http://localhost:3000"
  LOG_LEVEL: "debug"
  OAUTH2_EXPOSE_INTERNAL_ERRORS: "true"
