apiVersion: v1
kind: Service
metadata:
  name: kratos-public
  labels:
    app: kratos
    component: identity
spec:
  type: ClusterIP
  selector:
    app: kratos
    component: identity
  ports:
    - name: http-public
      port: 4433
      targetPort: 4433
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: kratos-admin
  labels:
    app: kratos
    component: identity
spec:
  type: ClusterIP
  selector:
    app: kratos
    component: identity
  ports:
    - name: http-admin
      port: 4434
      targetPort: 4434
      protocol: TCP
