apiVersion: v1
kind: Secret
metadata:
  name: kratos-oidc-secret
  labels:
    app: kratos
    component: identity
type: Opaque
stringData:
  SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS: '[{"id":"google","provider":"google","client_id":"780405820718-01k2a7ppuc32bol5fdpvdnjhm44sj4f4.apps.googleusercontent.com","client_secret":"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","mapper_url":"file:///etc/config/kratos/oidc.google.jsonnet","scope":["email","openid","profile"]}]'
