apiVersion: v1
kind: ConfigMap
metadata:
  name: web3-frontend-4-config
data:
  config.json: |
    {
      "gatewayUrl": "https://gateway.web3-local-dev.com",
      "clientId": "app-4-client-id",
      "authDomain": "app.web3-local-dev-2.net"
    }
