apiVersion: v1
kind: PersistentVolume
metadata:
  name: apisix-etcd-0-pv
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/apisix/etcd-0"
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - web3-lab
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: apisix-etcd-1-pv
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/apisix/etcd-1"
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - web3-lab-m02
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: apisix-etcd-2-pv
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/apisix/etcd-2"
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - web3-lab-m03
