apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: web3

resources:
- ../../base

patches:
- patch: |
    - op: add
      path: /spec/template/spec/containers/0/imagePullPolicy
      value: Never
  target:
    kind: Deployment
    name: mock-price-api
images:
- name: mock-price
  newName: mock-price
  newTag: 20260327_v0_0_82
