// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (account_id, status, metadata)
VALUES ($1, $2, $3)
RETURNING account_id, created_at, updated_at, last_login_at, status, metadata
`

type CreateAccountParams struct {
	AccountID pgtype.UUID `db:"account_id" json:"account_id"`
	Status    string      `db:"status" json:"status"`
	Metadata  []byte      `db:"metadata" json:"metadata"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount, arg.AccountID, arg.Status, arg.Metadata)
	var i Account
	err := row.Scan(
		&i.AccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.Status,
		&i.Metadata,
	)
	return i, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT account_id, created_at, updated_at, last_login_at, status, metadata FROM accounts WHERE account_id = $1
`

func (q *Queries) GetAccountByID(ctx context.Context, accountID pgtype.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, accountID)
	var i Account
	err := row.Scan(
		&i.AccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.Status,
		&i.Metadata,
	)
	return i, err
}

const getAccountByKratosIdentityID = `-- name: GetAccountByKratosIdentityID :one
SELECT a.account_id, a.created_at, a.updated_at, a.last_login_at, a.status, a.metadata
FROM accounts a
JOIN account_identities ai ON a.account_id = ai.account_id
WHERE ai.kratos_identity_id = $1
  AND ai.unlinked_at IS NULL
LIMIT 1
`

func (q *Queries) GetAccountByKratosIdentityID(ctx context.Context, kratosIdentityID pgtype.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByKratosIdentityID, kratosIdentityID)
	var i Account
	err := row.Scan(
		&i.AccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.Status,
		&i.Metadata,
	)
	return i, err
}

const updateAccount = `-- name: UpdateAccount :exec
UPDATE accounts
SET last_login_at = $1,
    status        = $2,
    metadata      = $3,
    updated_at    = CURRENT_TIMESTAMP
WHERE account_id = $4
`

type UpdateAccountParams struct {
	LastLoginAt pgtype.Timestamptz `db:"last_login_at" json:"last_login_at"`
	Status      string             `db:"status" json:"status"`
	Metadata    []byte             `db:"metadata" json:"metadata"`
	AccountID   pgtype.UUID        `db:"account_id" json:"account_id"`
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) error {
	_, err := q.db.Exec(ctx, updateAccount,
		arg.LastLoginAt,
		arg.Status,
		arg.Metadata,
		arg.AccountID,
	)
	return err
}

const updateAccountStatus = `-- name: UpdateAccountStatus :exec
UPDATE accounts
SET status     = $1,
    updated_at = CURRENT_TIMESTAMP
WHERE account_id = $2
`

type UpdateAccountStatusParams struct {
	Status    string      `db:"status" json:"status"`
	AccountID pgtype.UUID `db:"account_id" json:"account_id"`
}

func (q *Queries) UpdateAccountStatus(ctx context.Context, arg UpdateAccountStatusParams) error {
	_, err := q.db.Exec(ctx, updateAccountStatus, arg.Status, arg.AccountID)
	return err
}

const updateLastLogin = `-- name: UpdateLastLogin :exec
UPDATE accounts
SET last_login_at = $1,
    updated_at    = CURRENT_TIMESTAMP
WHERE account_id = $2
`

type UpdateLastLoginParams struct {
	LastLoginAt pgtype.Timestamptz `db:"last_login_at" json:"last_login_at"`
	AccountID   pgtype.UUID        `db:"account_id" json:"account_id"`
}

func (q *Queries) UpdateLastLogin(ctx context.Context, arg UpdateLastLoginParams) error {
	_, err := q.db.Exec(ctx, updateLastLogin, arg.LastLoginAt, arg.AccountID)
	return err
}
