// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO account_audit_logs (
    log_id, account_id, identity_id, event_type, event_status, event_message,
    session_id, kratos_session_id, ip_address, user_agent, provider_id, event_data
)
VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11, $12
)
RETURNING log_id, account_id, identity_id, event_type, event_status, event_message, session_id, kratos_session_id, ip_address, user_agent, provider_id, event_data, created_at
`

type CreateAuditLogParams struct {
	LogID           pgtype.UUID `db:"log_id" json:"log_id"`
	AccountID       pgtype.UUID `db:"account_id" json:"account_id"`
	IdentityID      pgtype.Text `db:"identity_id" json:"identity_id"`
	EventType       string      `db:"event_type" json:"event_type"`
	EventStatus     string      `db:"event_status" json:"event_status"`
	EventMessage    pgtype.Text `db:"event_message" json:"event_message"`
	SessionID       pgtype.UUID `db:"session_id" json:"session_id"`
	KratosSessionID pgtype.Text `db:"kratos_session_id" json:"kratos_session_id"`
	IpAddress       pgtype.Text `db:"ip_address" json:"ip_address"`
	UserAgent       pgtype.Text `db:"user_agent" json:"user_agent"`
	ProviderID      pgtype.Text `db:"provider_id" json:"provider_id"`
	EventData       []byte      `db:"event_data" json:"event_data"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AccountAuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.LogID,
		arg.AccountID,
		arg.IdentityID,
		arg.EventType,
		arg.EventStatus,
		arg.EventMessage,
		arg.SessionID,
		arg.KratosSessionID,
		arg.IpAddress,
		arg.UserAgent,
		arg.ProviderID,
		arg.EventData,
	)
	var i AccountAuditLog
	err := row.Scan(
		&i.LogID,
		&i.AccountID,
		&i.IdentityID,
		&i.EventType,
		&i.EventStatus,
		&i.EventMessage,
		&i.SessionID,
		&i.KratosSessionID,
		&i.IpAddress,
		&i.UserAgent,
		&i.ProviderID,
		&i.EventData,
		&i.CreatedAt,
	)
	return i, err
}

const getAuditLogsByAccountID = `-- name: GetAuditLogsByAccountID :many
SELECT log_id, account_id, identity_id, event_type, event_status, event_message, session_id, kratos_session_id, ip_address, user_agent, provider_id, event_data, created_at FROM account_audit_logs
WHERE account_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type GetAuditLogsByAccountIDParams struct {
	AccountID pgtype.UUID `db:"account_id" json:"account_id"`
	LogLimit  int32       `db:"log_limit" json:"log_limit"`
}

func (q *Queries) GetAuditLogsByAccountID(ctx context.Context, arg GetAuditLogsByAccountIDParams) ([]AccountAuditLog, error) {
	rows, err := q.db.Query(ctx, getAuditLogsByAccountID, arg.AccountID, arg.LogLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccountAuditLog{}
	for rows.Next() {
		var i AccountAuditLog
		if err := rows.Scan(
			&i.LogID,
			&i.AccountID,
			&i.IdentityID,
			&i.EventType,
			&i.EventStatus,
			&i.EventMessage,
			&i.SessionID,
			&i.KratosSessionID,
			&i.IpAddress,
			&i.UserAgent,
			&i.ProviderID,
			&i.EventData,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuditLogsByEventType = `-- name: GetAuditLogsByEventType :many
SELECT log_id, account_id, identity_id, event_type, event_status, event_message, session_id, kratos_session_id, ip_address, user_agent, provider_id, event_data, created_at FROM account_audit_logs
WHERE event_type = $1
ORDER BY created_at DESC
LIMIT $2
`

type GetAuditLogsByEventTypeParams struct {
	EventType string `db:"event_type" json:"event_type"`
	LogLimit  int32  `db:"log_limit" json:"log_limit"`
}

func (q *Queries) GetAuditLogsByEventType(ctx context.Context, arg GetAuditLogsByEventTypeParams) ([]AccountAuditLog, error) {
	rows, err := q.db.Query(ctx, getAuditLogsByEventType, arg.EventType, arg.LogLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccountAuditLog{}
	for rows.Next() {
		var i AccountAuditLog
		if err := rows.Scan(
			&i.LogID,
			&i.AccountID,
			&i.IdentityID,
			&i.EventType,
			&i.EventStatus,
			&i.EventMessage,
			&i.SessionID,
			&i.KratosSessionID,
			&i.IpAddress,
			&i.UserAgent,
			&i.ProviderID,
			&i.EventData,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuditLogsBySession = `-- name: GetAuditLogsBySession :many
SELECT log_id, account_id, identity_id, event_type, event_status, event_message, session_id, kratos_session_id, ip_address, user_agent, provider_id, event_data, created_at FROM account_audit_logs
WHERE session_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetAuditLogsBySession(ctx context.Context, sessionID pgtype.UUID) ([]AccountAuditLog, error) {
	rows, err := q.db.Query(ctx, getAuditLogsBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccountAuditLog{}
	for rows.Next() {
		var i AccountAuditLog
		if err := rows.Scan(
			&i.LogID,
			&i.AccountID,
			&i.IdentityID,
			&i.EventType,
			&i.EventStatus,
			&i.EventMessage,
			&i.SessionID,
			&i.KratosSessionID,
			&i.IpAddress,
			&i.UserAgent,
			&i.ProviderID,
			&i.EventData,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFailedLoginAttempts = `-- name: GetFailedLoginAttempts :many
SELECT log_id, account_id, identity_id, event_type, event_status, event_message, session_id, kratos_session_id, ip_address, user_agent, provider_id, event_data, created_at FROM account_audit_logs
WHERE event_type = 'LOGIN'
  AND event_status = 'FAILURE'
  AND identity_id = $1
  AND created_at >= $2
ORDER BY created_at DESC
`

type GetFailedLoginAttemptsParams struct {
	IdentityID pgtype.Text        `db:"identity_id" json:"identity_id"`
	Since      pgtype.Timestamptz `db:"since" json:"since"`
}

func (q *Queries) GetFailedLoginAttempts(ctx context.Context, arg GetFailedLoginAttemptsParams) ([]AccountAuditLog, error) {
	rows, err := q.db.Query(ctx, getFailedLoginAttempts, arg.IdentityID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccountAuditLog{}
	for rows.Next() {
		var i AccountAuditLog
		if err := rows.Scan(
			&i.LogID,
			&i.AccountID,
			&i.IdentityID,
			&i.EventType,
			&i.EventStatus,
			&i.EventMessage,
			&i.SessionID,
			&i.KratosSessionID,
			&i.IpAddress,
			&i.UserAgent,
			&i.ProviderID,
			&i.EventData,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
