// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clients.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAppClient = `-- name: CreateAppClient :one
INSERT INTO app_clients (
    id,
    name,
    oauth2_client_id,
    frontend_url,
    login_path,
    logout_url,
    allowed_cors_origins,
    jwt_secret,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, NOW(), NOW()
) RETURNING id, name, oauth2_client_id, frontend_url, login_path, logout_url, allowed_cors_origins, jwt_secret, created_at, updated_at, message_template_id
`

type CreateAppClientParams struct {
	ID                 pgtype.UUID `db:"id" json:"id"`
	Name               string      `db:"name" json:"name"`
	Oauth2ClientID     string      `db:"oauth2_client_id" json:"oauth2_client_id"`
	FrontendUrl        string      `db:"frontend_url" json:"frontend_url"`
	LoginPath          pgtype.Text `db:"login_path" json:"login_path"`
	LogoutUrl          pgtype.Text `db:"logout_url" json:"logout_url"`
	AllowedCorsOrigins []byte      `db:"allowed_cors_origins" json:"allowed_cors_origins"`
	JwtSecret          pgtype.Text `db:"jwt_secret" json:"jwt_secret"`
}

func (q *Queries) CreateAppClient(ctx context.Context, arg CreateAppClientParams) (AppClient, error) {
	row := q.db.QueryRow(ctx, createAppClient,
		arg.ID,
		arg.Name,
		arg.Oauth2ClientID,
		arg.FrontendUrl,
		arg.LoginPath,
		arg.LogoutUrl,
		arg.AllowedCorsOrigins,
		arg.JwtSecret,
	)
	var i AppClient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Oauth2ClientID,
		&i.FrontendUrl,
		&i.LoginPath,
		&i.LogoutUrl,
		&i.AllowedCorsOrigins,
		&i.JwtSecret,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MessageTemplateID,
	)
	return i, err
}

const deleteAppClient = `-- name: DeleteAppClient :exec
DELETE FROM app_clients
WHERE id = $1
`

func (q *Queries) DeleteAppClient(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAppClient, id)
	return err
}

const getAppClient = `-- name: GetAppClient :one
SELECT id, name, oauth2_client_id, frontend_url, login_path, logout_url, allowed_cors_origins, jwt_secret, created_at, updated_at, message_template_id FROM app_clients
WHERE id = $1
`

func (q *Queries) GetAppClient(ctx context.Context, id pgtype.UUID) (AppClient, error) {
	row := q.db.QueryRow(ctx, getAppClient, id)
	var i AppClient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Oauth2ClientID,
		&i.FrontendUrl,
		&i.LoginPath,
		&i.LogoutUrl,
		&i.AllowedCorsOrigins,
		&i.JwtSecret,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MessageTemplateID,
	)
	return i, err
}

const getAppClientByOAuth2ID = `-- name: GetAppClientByOAuth2ID :one
SELECT id, name, oauth2_client_id, frontend_url, login_path, logout_url, allowed_cors_origins, jwt_secret, created_at, updated_at, message_template_id FROM app_clients
WHERE oauth2_client_id = $1
`

func (q *Queries) GetAppClientByOAuth2ID(ctx context.Context, oauth2ClientID string) (AppClient, error) {
	row := q.db.QueryRow(ctx, getAppClientByOAuth2ID, oauth2ClientID)
	var i AppClient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Oauth2ClientID,
		&i.FrontendUrl,
		&i.LoginPath,
		&i.LogoutUrl,
		&i.AllowedCorsOrigins,
		&i.JwtSecret,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MessageTemplateID,
	)
	return i, err
}

const listAppClients = `-- name: ListAppClients :many
SELECT id, name, oauth2_client_id, frontend_url, login_path, logout_url, allowed_cors_origins, jwt_secret, created_at, updated_at, message_template_id FROM app_clients
ORDER BY created_at DESC
`

func (q *Queries) ListAppClients(ctx context.Context) ([]AppClient, error) {
	rows, err := q.db.Query(ctx, listAppClients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppClient{}
	for rows.Next() {
		var i AppClient
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Oauth2ClientID,
			&i.FrontendUrl,
			&i.LoginPath,
			&i.LogoutUrl,
			&i.AllowedCorsOrigins,
			&i.JwtSecret,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MessageTemplateID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAppClient = `-- name: UpdateAppClient :one
UPDATE app_clients
SET
    name = $2,
    frontend_url = $3,
    login_path = $4,
    logout_url = $5,
    allowed_cors_origins = $6,
    jwt_secret = $7,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, oauth2_client_id, frontend_url, login_path, logout_url, allowed_cors_origins, jwt_secret, created_at, updated_at, message_template_id
`

type UpdateAppClientParams struct {
	ID                 pgtype.UUID `db:"id" json:"id"`
	Name               string      `db:"name" json:"name"`
	FrontendUrl        string      `db:"frontend_url" json:"frontend_url"`
	LoginPath          pgtype.Text `db:"login_path" json:"login_path"`
	LogoutUrl          pgtype.Text `db:"logout_url" json:"logout_url"`
	AllowedCorsOrigins []byte      `db:"allowed_cors_origins" json:"allowed_cors_origins"`
	JwtSecret          pgtype.Text `db:"jwt_secret" json:"jwt_secret"`
}

func (q *Queries) UpdateAppClient(ctx context.Context, arg UpdateAppClientParams) (AppClient, error) {
	row := q.db.QueryRow(ctx, updateAppClient,
		arg.ID,
		arg.Name,
		arg.FrontendUrl,
		arg.LoginPath,
		arg.LogoutUrl,
		arg.AllowedCorsOrigins,
		arg.JwtSecret,
	)
	var i AppClient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Oauth2ClientID,
		&i.FrontendUrl,
		&i.LoginPath,
		&i.LogoutUrl,
		&i.AllowedCorsOrigins,
		&i.JwtSecret,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MessageTemplateID,
	)
	return i, err
}
