// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: identities.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccountIdentity = `-- name: CreateAccountIdentity :one
INSERT INTO account_identities (
    identity_id, account_id, kratos_identity_id, provider_id, provider_user_id,
    display_name, avatar_url, attributes, raw_data, verified, is_primary
)
VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10, $11
)
RETURNING identity_id, account_id, kratos_identity_id, provider_id, provider_user_id, display_name, avatar_url, attributes, raw_data, verified, is_primary, linked_at, last_used_at, updated_at, unlinked_at
`

type CreateAccountIdentityParams struct {
	IdentityID       pgtype.UUID `db:"identity_id" json:"identity_id"`
	AccountID        pgtype.UUID `db:"account_id" json:"account_id"`
	KratosIdentityID pgtype.UUID `db:"kratos_identity_id" json:"kratos_identity_id"`
	ProviderID       string      `db:"provider_id" json:"provider_id"`
	ProviderUserID   string      `db:"provider_user_id" json:"provider_user_id"`
	DisplayName      pgtype.Text `db:"display_name" json:"display_name"`
	AvatarUrl        pgtype.Text `db:"avatar_url" json:"avatar_url"`
	Attributes       []byte      `db:"attributes" json:"attributes"`
	RawData          []byte      `db:"raw_data" json:"raw_data"`
	Verified         bool        `db:"verified" json:"verified"`
	IsPrimary        bool        `db:"is_primary" json:"is_primary"`
}

func (q *Queries) CreateAccountIdentity(ctx context.Context, arg CreateAccountIdentityParams) (AccountIdentity, error) {
	row := q.db.QueryRow(ctx, createAccountIdentity,
		arg.IdentityID,
		arg.AccountID,
		arg.KratosIdentityID,
		arg.ProviderID,
		arg.ProviderUserID,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.Attributes,
		arg.RawData,
		arg.Verified,
		arg.IsPrimary,
	)
	var i AccountIdentity
	err := row.Scan(
		&i.IdentityID,
		&i.AccountID,
		&i.KratosIdentityID,
		&i.ProviderID,
		&i.ProviderUserID,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Attributes,
		&i.RawData,
		&i.Verified,
		&i.IsPrimary,
		&i.LinkedAt,
		&i.LastUsedAt,
		&i.UpdatedAt,
		&i.UnlinkedAt,
	)
	return i, err
}

const deleteAccountIdentity = `-- name: DeleteAccountIdentity :exec
DELETE FROM account_identities WHERE identity_id = $1
`

func (q *Queries) DeleteAccountIdentity(ctx context.Context, identityID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAccountIdentity, identityID)
	return err
}

const findAccountByEOA = `-- name: FindAccountByEOA :one
SELECT a.account_id, a.created_at, a.updated_at, a.last_login_at, a.status, a.metadata FROM accounts a
JOIN account_identities ai ON a.account_id = ai.account_id
WHERE ai.provider_id = 'eoa'
  AND ai.attributes->>'eoa_address' = $1
  AND ai.unlinked_at IS NULL
LIMIT 1
`

func (q *Queries) FindAccountByEOA(ctx context.Context, eoaAddress []byte) (Account, error) {
	row := q.db.QueryRow(ctx, findAccountByEOA, eoaAddress)
	var i Account
	err := row.Scan(
		&i.AccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.Status,
		&i.Metadata,
	)
	return i, err
}

const findAccountByEmail = `-- name: FindAccountByEmail :one
SELECT a.account_id, a.created_at, a.updated_at, a.last_login_at, a.status, a.metadata FROM accounts a
JOIN account_identities ai ON a.account_id = ai.account_id
WHERE ai.attributes->>'email' = $1
  AND ai.unlinked_at IS NULL
LIMIT 1
`

func (q *Queries) FindAccountByEmail(ctx context.Context, email []byte) (Account, error) {
	row := q.db.QueryRow(ctx, findAccountByEmail, email)
	var i Account
	err := row.Scan(
		&i.AccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.Status,
		&i.Metadata,
	)
	return i, err
}

const getAccountIdentitiesByAccountID = `-- name: GetAccountIdentitiesByAccountID :many
SELECT identity_id, account_id, kratos_identity_id, provider_id, provider_user_id, display_name, avatar_url, attributes, raw_data, verified, is_primary, linked_at, last_used_at, updated_at, unlinked_at FROM account_identities
WHERE account_id = $1
  AND unlinked_at IS NULL
ORDER BY linked_at DESC
`

func (q *Queries) GetAccountIdentitiesByAccountID(ctx context.Context, accountID pgtype.UUID) ([]AccountIdentity, error) {
	rows, err := q.db.Query(ctx, getAccountIdentitiesByAccountID, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccountIdentity{}
	for rows.Next() {
		var i AccountIdentity
		if err := rows.Scan(
			&i.IdentityID,
			&i.AccountID,
			&i.KratosIdentityID,
			&i.ProviderID,
			&i.ProviderUserID,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Attributes,
			&i.RawData,
			&i.Verified,
			&i.IsPrimary,
			&i.LinkedAt,
			&i.LastUsedAt,
			&i.UpdatedAt,
			&i.UnlinkedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAccountIdentity = `-- name: GetAccountIdentity :one
SELECT identity_id, account_id, kratos_identity_id, provider_id, provider_user_id, display_name, avatar_url, attributes, raw_data, verified, is_primary, linked_at, last_used_at, updated_at, unlinked_at FROM account_identities WHERE identity_id = $1
`

func (q *Queries) GetAccountIdentity(ctx context.Context, identityID pgtype.UUID) (AccountIdentity, error) {
	row := q.db.QueryRow(ctx, getAccountIdentity, identityID)
	var i AccountIdentity
	err := row.Scan(
		&i.IdentityID,
		&i.AccountID,
		&i.KratosIdentityID,
		&i.ProviderID,
		&i.ProviderUserID,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Attributes,
		&i.RawData,
		&i.Verified,
		&i.IsPrimary,
		&i.LinkedAt,
		&i.LastUsedAt,
		&i.UpdatedAt,
		&i.UnlinkedAt,
	)
	return i, err
}

const getAccountIdentityByKratosID = `-- name: GetAccountIdentityByKratosID :one
SELECT identity_id, account_id, kratos_identity_id, provider_id, provider_user_id, display_name, avatar_url, attributes, raw_data, verified, is_primary, linked_at, last_used_at, updated_at, unlinked_at FROM account_identities
WHERE kratos_identity_id = $1
  AND unlinked_at IS NULL
LIMIT 1
`

func (q *Queries) GetAccountIdentityByKratosID(ctx context.Context, kratosIdentityID pgtype.UUID) (AccountIdentity, error) {
	row := q.db.QueryRow(ctx, getAccountIdentityByKratosID, kratosIdentityID)
	var i AccountIdentity
	err := row.Scan(
		&i.IdentityID,
		&i.AccountID,
		&i.KratosIdentityID,
		&i.ProviderID,
		&i.ProviderUserID,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Attributes,
		&i.RawData,
		&i.Verified,
		&i.IsPrimary,
		&i.LinkedAt,
		&i.LastUsedAt,
		&i.UpdatedAt,
		&i.UnlinkedAt,
	)
	return i, err
}

const getAccountIdentityByProviderUserID = `-- name: GetAccountIdentityByProviderUserID :one
SELECT identity_id, account_id, kratos_identity_id, provider_id, provider_user_id, display_name, avatar_url, attributes, raw_data, verified, is_primary, linked_at, last_used_at, updated_at, unlinked_at FROM account_identities
WHERE provider_id = $1
  AND provider_user_id = $2
  AND unlinked_at IS NULL
LIMIT 1
`

type GetAccountIdentityByProviderUserIDParams struct {
	ProviderID     string `db:"provider_id" json:"provider_id"`
	ProviderUserID string `db:"provider_user_id" json:"provider_user_id"`
}

func (q *Queries) GetAccountIdentityByProviderUserID(ctx context.Context, arg GetAccountIdentityByProviderUserIDParams) (AccountIdentity, error) {
	row := q.db.QueryRow(ctx, getAccountIdentityByProviderUserID, arg.ProviderID, arg.ProviderUserID)
	var i AccountIdentity
	err := row.Scan(
		&i.IdentityID,
		&i.AccountID,
		&i.KratosIdentityID,
		&i.ProviderID,
		&i.ProviderUserID,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Attributes,
		&i.RawData,
		&i.Verified,
		&i.IsPrimary,
		&i.LinkedAt,
		&i.LastUsedAt,
		&i.UpdatedAt,
		&i.UnlinkedAt,
	)
	return i, err
}

const setPrimaryIdentityReset = `-- name: SetPrimaryIdentityReset :exec
UPDATE account_identities
SET is_primary = false,
    updated_at = CURRENT_TIMESTAMP
WHERE account_id = $1
`

func (q *Queries) SetPrimaryIdentityReset(ctx context.Context, accountID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, setPrimaryIdentityReset, accountID)
	return err
}

const setPrimaryIdentitySet = `-- name: SetPrimaryIdentitySet :exec
UPDATE account_identities
SET is_primary = true,
    updated_at = CURRENT_TIMESTAMP
WHERE identity_id = $1
  AND account_id = $2
`

type SetPrimaryIdentitySetParams struct {
	IdentityID pgtype.UUID `db:"identity_id" json:"identity_id"`
	AccountID  pgtype.UUID `db:"account_id" json:"account_id"`
}

func (q *Queries) SetPrimaryIdentitySet(ctx context.Context, arg SetPrimaryIdentitySetParams) error {
	_, err := q.db.Exec(ctx, setPrimaryIdentitySet, arg.IdentityID, arg.AccountID)
	return err
}

const softDeleteAccountIdentity = `-- name: SoftDeleteAccountIdentity :exec
UPDATE account_identities
SET unlinked_at = $1,
    updated_at  = CURRENT_TIMESTAMP
WHERE identity_id = $2
`

type SoftDeleteAccountIdentityParams struct {
	UnlinkedAt pgtype.Timestamptz `db:"unlinked_at" json:"unlinked_at"`
	IdentityID pgtype.UUID        `db:"identity_id" json:"identity_id"`
}

func (q *Queries) SoftDeleteAccountIdentity(ctx context.Context, arg SoftDeleteAccountIdentityParams) error {
	_, err := q.db.Exec(ctx, softDeleteAccountIdentity, arg.UnlinkedAt, arg.IdentityID)
	return err
}

const updateAccountIdentity = `-- name: UpdateAccountIdentity :exec
UPDATE account_identities
SET account_id   = $1,
    display_name = $2,
    avatar_url   = $3,
    attributes   = $4,
    raw_data     = $5,
    verified     = $6,
    is_primary   = $7,
    last_used_at = $8,
    updated_at   = CURRENT_TIMESTAMP
WHERE identity_id = $9
`

type UpdateAccountIdentityParams struct {
	AccountID   pgtype.UUID        `db:"account_id" json:"account_id"`
	DisplayName pgtype.Text        `db:"display_name" json:"display_name"`
	AvatarUrl   pgtype.Text        `db:"avatar_url" json:"avatar_url"`
	Attributes  []byte             `db:"attributes" json:"attributes"`
	RawData     []byte             `db:"raw_data" json:"raw_data"`
	Verified    bool               `db:"verified" json:"verified"`
	IsPrimary   bool               `db:"is_primary" json:"is_primary"`
	LastUsedAt  pgtype.Timestamptz `db:"last_used_at" json:"last_used_at"`
	IdentityID  pgtype.UUID        `db:"identity_id" json:"identity_id"`
}

func (q *Queries) UpdateAccountIdentity(ctx context.Context, arg UpdateAccountIdentityParams) error {
	_, err := q.db.Exec(ctx, updateAccountIdentity,
		arg.AccountID,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.Attributes,
		arg.RawData,
		arg.Verified,
		arg.IsPrimary,
		arg.LastUsedAt,
		arg.IdentityID,
	)
	return err
}

const updateIdentityLastUsed = `-- name: UpdateIdentityLastUsed :exec
UPDATE account_identities
SET last_used_at = $1,
    updated_at   = CURRENT_TIMESTAMP
WHERE identity_id = $2
`

type UpdateIdentityLastUsedParams struct {
	LastUsedAt pgtype.Timestamptz `db:"last_used_at" json:"last_used_at"`
	IdentityID pgtype.UUID        `db:"identity_id" json:"identity_id"`
}

func (q *Queries) UpdateIdentityLastUsed(ctx context.Context, arg UpdateIdentityLastUsedParams) error {
	_, err := q.db.Exec(ctx, updateIdentityLastUsed, arg.LastUsedAt, arg.IdentityID)
	return err
}
