// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: message_templates.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAppClientsByTemplateID = `-- name: CountAppClientsByTemplateID :one
SELECT COUNT(*) FROM app_clients
WHERE message_template_id = $1
`

func (q *Queries) CountAppClientsByTemplateID(ctx context.Context, messageTemplateID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAppClientsByTemplateID, messageTemplateID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMessageTemplate = `-- name: CreateMessageTemplate :one
INSERT INTO message_templates (
    name, protocol, statement, domain, uri, chain_id, version, nonce_ttl_secs
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, name, protocol, statement, domain, uri, chain_id, version, nonce_ttl_secs, created_at, updated_at
`

type CreateMessageTemplateParams struct {
	Name         string `db:"name" json:"name"`
	Protocol     string `db:"protocol" json:"protocol"`
	Statement    string `db:"statement" json:"statement"`
	Domain       string `db:"domain" json:"domain"`
	Uri          string `db:"uri" json:"uri"`
	ChainID      int32  `db:"chain_id" json:"chain_id"`
	Version      string `db:"version" json:"version"`
	NonceTtlSecs int32  `db:"nonce_ttl_secs" json:"nonce_ttl_secs"`
}

func (q *Queries) CreateMessageTemplate(ctx context.Context, arg CreateMessageTemplateParams) (MessageTemplate, error) {
	row := q.db.QueryRow(ctx, createMessageTemplate,
		arg.Name,
		arg.Protocol,
		arg.Statement,
		arg.Domain,
		arg.Uri,
		arg.ChainID,
		arg.Version,
		arg.NonceTtlSecs,
	)
	var i MessageTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Protocol,
		&i.Statement,
		&i.Domain,
		&i.Uri,
		&i.ChainID,
		&i.Version,
		&i.NonceTtlSecs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMessageTemplate = `-- name: DeleteMessageTemplate :exec
DELETE FROM message_templates
WHERE id = $1
`

func (q *Queries) DeleteMessageTemplate(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMessageTemplate, id)
	return err
}

const getAppClientWithTemplate = `-- name: GetAppClientWithTemplate :one
SELECT ac.id, ac.name, ac.oauth2_client_id, ac.frontend_url, ac.login_path, ac.logout_url, ac.allowed_cors_origins, ac.jwt_secret, ac.created_at, ac.updated_at, ac.message_template_id, mt.id AS template_id, mt.name AS template_name,
       mt.protocol AS template_protocol, mt.statement AS template_statement,
       mt.domain AS template_domain, mt.uri AS template_uri,
       mt.chain_id AS template_chain_id, mt.version AS template_version,
       mt.nonce_ttl_secs AS template_nonce_ttl_secs
FROM app_clients ac
LEFT JOIN message_templates mt ON ac.message_template_id = mt.id
WHERE ac.id = $1
`

type GetAppClientWithTemplateRow struct {
	ID                   pgtype.UUID        `db:"id" json:"id"`
	Name                 string             `db:"name" json:"name"`
	Oauth2ClientID       string             `db:"oauth2_client_id" json:"oauth2_client_id"`
	FrontendUrl          string             `db:"frontend_url" json:"frontend_url"`
	LoginPath            pgtype.Text        `db:"login_path" json:"login_path"`
	LogoutUrl            pgtype.Text        `db:"logout_url" json:"logout_url"`
	AllowedCorsOrigins   []byte             `db:"allowed_cors_origins" json:"allowed_cors_origins"`
	JwtSecret            pgtype.Text        `db:"jwt_secret" json:"jwt_secret"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	MessageTemplateID    pgtype.UUID        `db:"message_template_id" json:"message_template_id"`
	TemplateID           pgtype.UUID        `db:"template_id" json:"template_id"`
	TemplateName         pgtype.Text        `db:"template_name" json:"template_name"`
	TemplateProtocol     pgtype.Text        `db:"template_protocol" json:"template_protocol"`
	TemplateStatement    pgtype.Text        `db:"template_statement" json:"template_statement"`
	TemplateDomain       pgtype.Text        `db:"template_domain" json:"template_domain"`
	TemplateUri          pgtype.Text        `db:"template_uri" json:"template_uri"`
	TemplateChainID      pgtype.Int4        `db:"template_chain_id" json:"template_chain_id"`
	TemplateVersion      pgtype.Text        `db:"template_version" json:"template_version"`
	TemplateNonceTtlSecs pgtype.Int4        `db:"template_nonce_ttl_secs" json:"template_nonce_ttl_secs"`
}

func (q *Queries) GetAppClientWithTemplate(ctx context.Context, id pgtype.UUID) (GetAppClientWithTemplateRow, error) {
	row := q.db.QueryRow(ctx, getAppClientWithTemplate, id)
	var i GetAppClientWithTemplateRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Oauth2ClientID,
		&i.FrontendUrl,
		&i.LoginPath,
		&i.LogoutUrl,
		&i.AllowedCorsOrigins,
		&i.JwtSecret,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MessageTemplateID,
		&i.TemplateID,
		&i.TemplateName,
		&i.TemplateProtocol,
		&i.TemplateStatement,
		&i.TemplateDomain,
		&i.TemplateUri,
		&i.TemplateChainID,
		&i.TemplateVersion,
		&i.TemplateNonceTtlSecs,
	)
	return i, err
}

const getMessageTemplate = `-- name: GetMessageTemplate :one
SELECT id, name, protocol, statement, domain, uri, chain_id, version, nonce_ttl_secs, created_at, updated_at FROM message_templates
WHERE id = $1
`

func (q *Queries) GetMessageTemplate(ctx context.Context, id pgtype.UUID) (MessageTemplate, error) {
	row := q.db.QueryRow(ctx, getMessageTemplate, id)
	var i MessageTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Protocol,
		&i.Statement,
		&i.Domain,
		&i.Uri,
		&i.ChainID,
		&i.Version,
		&i.NonceTtlSecs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMessageTemplateByName = `-- name: GetMessageTemplateByName :one
SELECT id, name, protocol, statement, domain, uri, chain_id, version, nonce_ttl_secs, created_at, updated_at FROM message_templates
WHERE name = $1
`

func (q *Queries) GetMessageTemplateByName(ctx context.Context, name string) (MessageTemplate, error) {
	row := q.db.QueryRow(ctx, getMessageTemplateByName, name)
	var i MessageTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Protocol,
		&i.Statement,
		&i.Domain,
		&i.Uri,
		&i.ChainID,
		&i.Version,
		&i.NonceTtlSecs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMessageTemplates = `-- name: ListMessageTemplates :many
SELECT id, name, protocol, statement, domain, uri, chain_id, version, nonce_ttl_secs, created_at, updated_at FROM message_templates
ORDER BY created_at DESC
`

func (q *Queries) ListMessageTemplates(ctx context.Context) ([]MessageTemplate, error) {
	rows, err := q.db.Query(ctx, listMessageTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MessageTemplate{}
	for rows.Next() {
		var i MessageTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Protocol,
			&i.Statement,
			&i.Domain,
			&i.Uri,
			&i.ChainID,
			&i.Version,
			&i.NonceTtlSecs,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMessageTemplate = `-- name: UpdateMessageTemplate :one
UPDATE message_templates
SET
    name = COALESCE(NULLIF($2, ''), name),
    statement = COALESCE(NULLIF($3, ''), statement),
    domain = COALESCE(NULLIF($4, ''), domain),
    uri = COALESCE(NULLIF($5, ''), uri),
    chain_id = COALESCE($6, chain_id),
    version = COALESCE(NULLIF($7, ''), version),
    nonce_ttl_secs = COALESCE($8, nonce_ttl_secs),
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, protocol, statement, domain, uri, chain_id, version, nonce_ttl_secs, created_at, updated_at
`

type UpdateMessageTemplateParams struct {
	ID           pgtype.UUID `db:"id" json:"id"`
	Column2      interface{} `db:"column_2" json:"column_2"`
	Column3      interface{} `db:"column_3" json:"column_3"`
	Column4      interface{} `db:"column_4" json:"column_4"`
	Column5      interface{} `db:"column_5" json:"column_5"`
	ChainID      int32       `db:"chain_id" json:"chain_id"`
	Column7      interface{} `db:"column_7" json:"column_7"`
	NonceTtlSecs int32       `db:"nonce_ttl_secs" json:"nonce_ttl_secs"`
}

func (q *Queries) UpdateMessageTemplate(ctx context.Context, arg UpdateMessageTemplateParams) (MessageTemplate, error) {
	row := q.db.QueryRow(ctx, updateMessageTemplate,
		arg.ID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.ChainID,
		arg.Column7,
		arg.NonceTtlSecs,
	)
	var i MessageTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Protocol,
		&i.Statement,
		&i.Domain,
		&i.Uri,
		&i.ChainID,
		&i.Version,
		&i.NonceTtlSecs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
