// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	AccountID   pgtype.UUID        `db:"account_id" json:"account_id"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	LastLoginAt pgtype.Timestamptz `db:"last_login_at" json:"last_login_at"`
	Status      string             `db:"status" json:"status"`
	Metadata    []byte             `db:"metadata" json:"metadata"`
}

type AccountAuditLog struct {
	LogID           pgtype.UUID        `db:"log_id" json:"log_id"`
	AccountID       pgtype.UUID        `db:"account_id" json:"account_id"`
	IdentityID      pgtype.Text        `db:"identity_id" json:"identity_id"`
	EventType       string             `db:"event_type" json:"event_type"`
	EventStatus     string             `db:"event_status" json:"event_status"`
	EventMessage    pgtype.Text        `db:"event_message" json:"event_message"`
	SessionID       pgtype.UUID        `db:"session_id" json:"session_id"`
	KratosSessionID pgtype.Text        `db:"kratos_session_id" json:"kratos_session_id"`
	IpAddress       pgtype.Text        `db:"ip_address" json:"ip_address"`
	UserAgent       pgtype.Text        `db:"user_agent" json:"user_agent"`
	ProviderID      pgtype.Text        `db:"provider_id" json:"provider_id"`
	EventData       []byte             `db:"event_data" json:"event_data"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type AccountIdentity struct {
	IdentityID       pgtype.UUID        `db:"identity_id" json:"identity_id"`
	AccountID        pgtype.UUID        `db:"account_id" json:"account_id"`
	KratosIdentityID pgtype.UUID        `db:"kratos_identity_id" json:"kratos_identity_id"`
	ProviderID       string             `db:"provider_id" json:"provider_id"`
	ProviderUserID   string             `db:"provider_user_id" json:"provider_user_id"`
	DisplayName      pgtype.Text        `db:"display_name" json:"display_name"`
	AvatarUrl        pgtype.Text        `db:"avatar_url" json:"avatar_url"`
	Attributes       []byte             `db:"attributes" json:"attributes"`
	RawData          []byte             `db:"raw_data" json:"raw_data"`
	Verified         bool               `db:"verified" json:"verified"`
	IsPrimary        bool               `db:"is_primary" json:"is_primary"`
	LinkedAt         pgtype.Timestamptz `db:"linked_at" json:"linked_at"`
	LastUsedAt       pgtype.Timestamptz `db:"last_used_at" json:"last_used_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	UnlinkedAt       pgtype.Timestamptz `db:"unlinked_at" json:"unlinked_at"`
}

type AccountMergeHistory struct {
	MergeID               pgtype.UUID        `db:"merge_id" json:"merge_id"`
	SourceAccountID       pgtype.UUID        `db:"source_account_id" json:"source_account_id"`
	TargetAccountID       pgtype.UUID        `db:"target_account_id" json:"target_account_id"`
	MergedAt              pgtype.Timestamptz `db:"merged_at" json:"merged_at"`
	MergedBy              pgtype.UUID        `db:"merged_by" json:"merged_by"`
	Reason                pgtype.Text        `db:"reason" json:"reason"`
	IdentitiesTransferred pgtype.Int4        `db:"identities_transferred" json:"identities_transferred"`
	Metadata              []byte             `db:"metadata" json:"metadata"`
}

type AccountSession struct {
	SessionID       pgtype.UUID        `db:"session_id" json:"session_id"`
	AccountID       pgtype.UUID        `db:"account_id" json:"account_id"`
	IdentityID      pgtype.UUID        `db:"identity_id" json:"identity_id"`
	KratosSessionID pgtype.UUID        `db:"kratos_session_id" json:"kratos_session_id"`
	IpAddress       pgtype.Text        `db:"ip_address" json:"ip_address"`
	UserAgent       pgtype.Text        `db:"user_agent" json:"user_agent"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ExpiresAt       pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	RevokedAt       pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	LastActivityAt  pgtype.Timestamptz `db:"last_activity_at" json:"last_activity_at"`
}

type AppClient struct {
	ID                 pgtype.UUID        `db:"id" json:"id"`
	Name               string             `db:"name" json:"name"`
	Oauth2ClientID     string             `db:"oauth2_client_id" json:"oauth2_client_id"`
	FrontendUrl        string             `db:"frontend_url" json:"frontend_url"`
	LoginPath          pgtype.Text        `db:"login_path" json:"login_path"`
	LogoutUrl          pgtype.Text        `db:"logout_url" json:"logout_url"`
	AllowedCorsOrigins []byte             `db:"allowed_cors_origins" json:"allowed_cors_origins"`
	JwtSecret          pgtype.Text        `db:"jwt_secret" json:"jwt_secret"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	MessageTemplateID  pgtype.UUID        `db:"message_template_id" json:"message_template_id"`
}

type IdentityProvider struct {
	ProviderID    string             `db:"provider_id" json:"provider_id"`
	ProviderName  string             `db:"provider_name" json:"provider_name"`
	ProviderType  string             `db:"provider_type" json:"provider_type"`
	Enabled       bool               `db:"enabled" json:"enabled"`
	Configuration []byte             `db:"configuration" json:"configuration"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type MessageTemplate struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	Name         string             `db:"name" json:"name"`
	Protocol     string             `db:"protocol" json:"protocol"`
	Statement    string             `db:"statement" json:"statement"`
	Domain       string             `db:"domain" json:"domain"`
	Uri          string             `db:"uri" json:"uri"`
	ChainID      int32              `db:"chain_id" json:"chain_id"`
	Version      string             `db:"version" json:"version"`
	NonceTtlSecs int32              `db:"nonce_ttl_secs" json:"nonce_ttl_secs"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}
