// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: providers.sql

package sqlc

import (
	"context"
)

const getIdentityProvider = `-- name: GetIdentityProvider :one
SELECT provider_id, provider_name, provider_type, enabled, configuration, created_at, updated_at FROM identity_providers WHERE provider_id = $1
`

func (q *Queries) GetIdentityProvider(ctx context.Context, providerID string) (IdentityProvider, error) {
	row := q.db.QueryRow(ctx, getIdentityProvider, providerID)
	var i IdentityProvider
	err := row.Scan(
		&i.ProviderID,
		&i.ProviderName,
		&i.ProviderType,
		&i.Enabled,
		&i.Configuration,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listIdentityProviders = `-- name: ListIdentityProviders :many
SELECT provider_id, provider_name, provider_type, enabled, configuration, created_at, updated_at FROM identity_providers
WHERE ($1::boolean = false OR enabled = true)
ORDER BY provider_id
`

func (q *Queries) ListIdentityProviders(ctx context.Context, onlyEnabled bool) ([]IdentityProvider, error) {
	rows, err := q.db.Query(ctx, listIdentityProviders, onlyEnabled)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IdentityProvider{}
	for rows.Next() {
		var i IdentityProvider
		if err := rows.Scan(
			&i.ProviderID,
			&i.ProviderName,
			&i.ProviderType,
			&i.Enabled,
			&i.Configuration,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIdentityProvider = `-- name: UpdateIdentityProvider :exec
UPDATE identity_providers
SET provider_name = $1,
    provider_type = $2,
    enabled       = $3,
    configuration = $4,
    updated_at    = CURRENT_TIMESTAMP
WHERE provider_id = $5
`

type UpdateIdentityProviderParams struct {
	ProviderName  string `db:"provider_name" json:"provider_name"`
	ProviderType  string `db:"provider_type" json:"provider_type"`
	Enabled       bool   `db:"enabled" json:"enabled"`
	Configuration []byte `db:"configuration" json:"configuration"`
	ProviderID    string `db:"provider_id" json:"provider_id"`
}

func (q *Queries) UpdateIdentityProvider(ctx context.Context, arg UpdateIdentityProviderParams) error {
	_, err := q.db.Exec(ctx, updateIdentityProvider,
		arg.ProviderName,
		arg.ProviderType,
		arg.Enabled,
		arg.Configuration,
		arg.ProviderID,
	)
	return err
}
