// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cleanupExpiredSessions = `-- name: CleanupExpiredSessions :execrows
DELETE FROM account_sessions
WHERE expires_at < CURRENT_TIMESTAMP
   OR revoked_at IS NOT NULL
`

func (q *Queries) CleanupExpiredSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, cleanupExpiredSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createAccountSession = `-- name: CreateAccountSession :one
INSERT INTO account_sessions (
    session_id, account_id, identity_id, kratos_session_id,
    ip_address, user_agent, expires_at
)
VALUES (
    $1, $2, $3, $4,
    $5, $6, $7
)
RETURNING session_id, account_id, identity_id, kratos_session_id, ip_address, user_agent, created_at, expires_at, revoked_at, last_activity_at
`

type CreateAccountSessionParams struct {
	SessionID       pgtype.UUID        `db:"session_id" json:"session_id"`
	AccountID       pgtype.UUID        `db:"account_id" json:"account_id"`
	IdentityID      pgtype.UUID        `db:"identity_id" json:"identity_id"`
	KratosSessionID pgtype.UUID        `db:"kratos_session_id" json:"kratos_session_id"`
	IpAddress       pgtype.Text        `db:"ip_address" json:"ip_address"`
	UserAgent       pgtype.Text        `db:"user_agent" json:"user_agent"`
	ExpiresAt       pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreateAccountSession(ctx context.Context, arg CreateAccountSessionParams) (AccountSession, error) {
	row := q.db.QueryRow(ctx, createAccountSession,
		arg.SessionID,
		arg.AccountID,
		arg.IdentityID,
		arg.KratosSessionID,
		arg.IpAddress,
		arg.UserAgent,
		arg.ExpiresAt,
	)
	var i AccountSession
	err := row.Scan(
		&i.SessionID,
		&i.AccountID,
		&i.IdentityID,
		&i.KratosSessionID,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastActivityAt,
	)
	return i, err
}

const getAccountSession = `-- name: GetAccountSession :one
SELECT session_id, account_id, identity_id, kratos_session_id, ip_address, user_agent, created_at, expires_at, revoked_at, last_activity_at FROM account_sessions WHERE session_id = $1
`

func (q *Queries) GetAccountSession(ctx context.Context, sessionID pgtype.UUID) (AccountSession, error) {
	row := q.db.QueryRow(ctx, getAccountSession, sessionID)
	var i AccountSession
	err := row.Scan(
		&i.SessionID,
		&i.AccountID,
		&i.IdentityID,
		&i.KratosSessionID,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastActivityAt,
	)
	return i, err
}

const getAccountSessionByKratosSessionID = `-- name: GetAccountSessionByKratosSessionID :one
SELECT session_id, account_id, identity_id, kratos_session_id, ip_address, user_agent, created_at, expires_at, revoked_at, last_activity_at FROM account_sessions
WHERE kratos_session_id = $1
LIMIT 1
`

func (q *Queries) GetAccountSessionByKratosSessionID(ctx context.Context, kratosSessionID pgtype.UUID) (AccountSession, error) {
	row := q.db.QueryRow(ctx, getAccountSessionByKratosSessionID, kratosSessionID)
	var i AccountSession
	err := row.Scan(
		&i.SessionID,
		&i.AccountID,
		&i.IdentityID,
		&i.KratosSessionID,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastActivityAt,
	)
	return i, err
}

const getActiveSessionsByAccountID = `-- name: GetActiveSessionsByAccountID :many
SELECT session_id, account_id, identity_id, kratos_session_id, ip_address, user_agent, created_at, expires_at, revoked_at, last_activity_at FROM account_sessions
WHERE account_id = $1
  AND revoked_at IS NULL
  AND expires_at > CURRENT_TIMESTAMP
ORDER BY created_at DESC
`

func (q *Queries) GetActiveSessionsByAccountID(ctx context.Context, accountID pgtype.UUID) ([]AccountSession, error) {
	rows, err := q.db.Query(ctx, getActiveSessionsByAccountID, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccountSession{}
	for rows.Next() {
		var i AccountSession
		if err := rows.Scan(
			&i.SessionID,
			&i.AccountID,
			&i.IdentityID,
			&i.KratosSessionID,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.LastActivityAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAccountSessions = `-- name: RevokeAccountSessions :exec
UPDATE account_sessions
SET revoked_at = $1
WHERE account_id = $2
  AND revoked_at IS NULL
`

type RevokeAccountSessionsParams struct {
	RevokedAt pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	AccountID pgtype.UUID        `db:"account_id" json:"account_id"`
}

func (q *Queries) RevokeAccountSessions(ctx context.Context, arg RevokeAccountSessionsParams) error {
	_, err := q.db.Exec(ctx, revokeAccountSessions, arg.RevokedAt, arg.AccountID)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE account_sessions
SET revoked_at = $1
WHERE session_id = $2
`

type RevokeSessionParams struct {
	RevokedAt pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	SessionID pgtype.UUID        `db:"session_id" json:"session_id"`
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) error {
	_, err := q.db.Exec(ctx, revokeSession, arg.RevokedAt, arg.SessionID)
	return err
}

const updateSessionActivity = `-- name: UpdateSessionActivity :exec
UPDATE account_sessions
SET last_activity_at = $1
WHERE session_id = $2
`

type UpdateSessionActivityParams struct {
	LastActivityAt pgtype.Timestamptz `db:"last_activity_at" json:"last_activity_at"`
	SessionID      pgtype.UUID        `db:"session_id" json:"session_id"`
}

func (q *Queries) UpdateSessionActivity(ctx context.Context, arg UpdateSessionActivityParams) error {
	_, err := q.db.Exec(ctx, updateSessionActivity, arg.LastActivityAt, arg.SessionID)
	return err
}
